import {
  TRACE_SCHEMA_VERSION,
  type GlassWebTrace,
  type TraceEntity,
} from './types';

const entity = (
  value: Omit<TraceEntity, 'firstSeen' | 'lastSeen' | 'evidenceIds'> & {
    firstSeen?: number;
    lastSeen?: number;
    evidenceIds?: string[];
  },
): TraceEntity => ({
  firstSeen: 0,
  lastSeen: 6200,
  evidenceIds: [`ev-${value.id}`],
  ...value,
});

const withEvidence = (trace: GlassWebTrace): GlassWebTrace => ({
  ...trace,
  evidence: [
    ...trace.entities.map((item) => ({
      id: `ev-${item.id}`,
      source: 'dom' as const,
      explanation: `The instrumented demo directly recorded “${item.humanLabel}”.`,
      eventIds: trace.events
        .filter((event) => event.entityIds.includes(item.id))
        .map((event) => event.id),
    })),
    ...trace.relations.map((relation) => ({
      id: `ev-${relation.id}`,
      source: 'instrumentation' as const,
      explanation: relation.explanation,
      eventIds: trace.events
        .filter((event) =>
          event.entityIds.some(
            (id) => id === relation.from || id === relation.to,
          ),
        )
        .map((event) => event.id),
    })),
  ],
});

export const demoTrace: GlassWebTrace = withEvidence({
  schemaVersion: TRACE_SCHEMA_VERSION,
  id: 'demo-orbit-pricing',
  title: 'Orbit pricing demo',
  createdAt: '2026-09-02T18:00:00.000Z',
  durationMs: 6200,
  page: {
    origin: 'https://orbit.systems',
    url: 'https://orbit.systems/pricing?region=••',
    title: 'Orbit pricing page',
    viewport: { width: 1440, height: 900, devicePixelRatio: 2 },
  },
  entities: [
    entity({
      id: 'visible-page',
      kind: 'visual-element',
      layer: 'visible',
      humanLabel: 'Pricing page',
      technicalLabel: 'document /pricing',
      description: 'The complete page a visitor receives and interacts with.',
      certainty: 'observed',
    }),
    entity({
      id: 'visible-price',
      kind: 'visual-element',
      layer: 'visible',
      humanLabel: 'Regional Pro price',
      technicalLabel: 'R 1,499 / month',
      description: 'The price currently painted into the Pro plan card.',
      certainty: 'observed',
      bounds: { x: 710, y: 326, width: 210, height: 54 },
    }),
    entity({
      id: 'visible-cta',
      kind: 'visual-element',
      layer: 'visible',
      humanLabel: 'Start Pro button',
      technicalLabel: 'button[data-plan="pro"]',
      description: 'Starts the paid subscription checkout journey.',
      certainty: 'observed',
      bounds: { x: 710, y: 512, width: 240, height: 48 },
    }),
    entity({
      id: 'visible-toggle',
      kind: 'visual-element',
      layer: 'visible',
      humanLabel: 'Annual billing toggle',
      technicalLabel: 'button[aria-pressed]',
      description: 'Changes which billing period and prices are displayed.',
      certainty: 'observed',
    }),
    entity({
      id: 'visible-newsletter',
      kind: 'visual-element',
      layer: 'visible',
      humanLabel: 'Product updates form',
      technicalLabel: 'form#updates',
      description:
        'Sends an email address to the mailing provider after consent.',
      certainty: 'observed',
    }),
    entity({
      id: 'structure-page',
      kind: 'dom-node',
      layer: 'structure',
      humanLabel: 'Pricing view',
      technicalLabel: '<PricingPage>',
      description: 'The rendered component containing the plan comparison.',
      certainty: 'observed',
    }),
    entity({
      id: 'structure-price',
      kind: 'dom-node',
      layer: 'structure',
      humanLabel: 'Price output',
      technicalLabel: '<RegionalPrice plan="pro">',
      description: 'The DOM node updated when regional pricing resolves.',
      certainty: 'observed',
    }),
    entity({
      id: 'structure-cta',
      kind: 'dom-node',
      layer: 'structure',
      humanLabel: 'Checkout control',
      technicalLabel: '<CheckoutAction plan="pro">',
      description: 'An interactive control with a registered click listener.',
      certainty: 'observed',
    }),
    entity({
      id: 'structure-toggle',
      kind: 'dom-node',
      layer: 'structure',
      humanLabel: 'Billing period control',
      technicalLabel: '<BillingPeriodToggle>',
      description: 'Switches the pricing view between monthly and annual data.',
      certainty: 'observed',
    }),
    entity({
      id: 'structure-newsletter',
      kind: 'dom-node',
      layer: 'structure',
      humanLabel: 'Updates form',
      technicalLabel: '<UpdatesForm>',
      description: 'The form boundary and its submit event.',
      certainty: 'observed',
    }),
    entity({
      id: 'behaviour-hydrate',
      kind: 'script',
      layer: 'behaviour',
      humanLabel: 'Bring pricing controls alive',
      technicalLabel: 'pricing-client.tsx:hydrate()',
      description: 'Client code attaches the interactive pricing behaviour.',
      certainty: 'observed',
    }),
    entity({
      id: 'behaviour-price',
      kind: 'interaction',
      layer: 'behaviour',
      humanLabel: 'Format the regional price',
      technicalLabel: 'formatRegionalPrice(ZA)',
      description:
        'Turns the returned amount and currency into the visible label.',
      certainty: 'correlated',
    }),
    entity({
      id: 'behaviour-checkout',
      kind: 'interaction',
      layer: 'behaviour',
      humanLabel: 'Create a checkout',
      technicalLabel: 'checkout.start("pro")',
      description: 'Builds the request after the visitor confirms the plan.',
      certainty: 'observed',
    }),
    entity({
      id: 'behaviour-billing',
      kind: 'interaction',
      layer: 'behaviour',
      humanLabel: 'Change billing period',
      technicalLabel: 'pricing.setPeriod("annual")',
      description: 'Updates plan prices without leaving the page.',
      certainty: 'observed',
    }),
    entity({
      id: 'behaviour-analytics',
      kind: 'interaction',
      layer: 'behaviour',
      humanLabel: 'Measure plan interest',
      technicalLabel: 'analytics.track("Plan Viewed")',
      description: 'Records that the Pro plan entered the viewport.',
      certainty: 'observed',
    }),
    entity({
      id: 'behaviour-newsletter',
      kind: 'interaction',
      layer: 'behaviour',
      humanLabel: 'Subscribe for updates',
      technicalLabel: 'updates.subscribe()',
      description: 'Handles the explicit newsletter form submission.',
      certainty: 'observed',
    }),
    entity({
      id: 'network-document',
      kind: 'request',
      layer: 'network',
      humanLabel: 'Load pricing page',
      technicalLabel: 'GET /pricing',
      description: 'Initial HTML document returned by Orbit.',
      certainty: 'observed',
      attributes: { status: 200, durationMs: 96, mime: 'text/html' },
    }),
    entity({
      id: 'network-price',
      kind: 'request',
      layer: 'network',
      humanLabel: 'Load South African pricing',
      technicalLabel: 'GET /api/pricing?region=••',
      description: 'Returns currency and plan amounts for the selected region.',
      certainty: 'observed',
      attributes: { status: 200, durationMs: 118, mime: 'application/json' },
    }),
    entity({
      id: 'network-checkout',
      kind: 'request',
      layer: 'network',
      humanLabel: 'Open checkout session',
      technicalLabel: 'POST /api/checkout',
      description: 'Creates one short-lived Stripe checkout session.',
      certainty: 'observed',
      attributes: { status: 201, durationMs: 184, mime: 'application/json' },
    }),
    entity({
      id: 'network-analytics',
      kind: 'request',
      layer: 'network',
      humanLabel: 'Send product analytics',
      technicalLabel: 'POST /v1/track',
      description: 'Sends a plan-view event without captured field values.',
      certainty: 'observed',
      attributes: { status: 200, durationMs: 72, mime: 'application/json' },
    }),
    entity({
      id: 'network-newsletter',
      kind: 'request',
      layer: 'network',
      humanLabel: 'Add newsletter subscriber',
      technicalLabel: 'POST /client/subscriptions',
      description: 'Writes a consented subscriber to the mailing provider.',
      certainty: 'observed',
      attributes: { status: 202, durationMs: 151, mime: 'application/json' },
    }),
    entity({
      id: 'service-orbit',
      kind: 'service',
      layer: 'service',
      humanLabel: 'Orbit application',
      technicalLabel: 'orbit.systems',
      description:
        'The first-party application serving the document and scripts.',
      certainty: 'observed',
    }),
    entity({
      id: 'service-pricing',
      kind: 'service',
      layer: 'service',
      humanLabel: 'Regional pricing service',
      technicalLabel: 'pricing.orbit.systems',
      description: 'Orbit-owned service that returns regional plan pricing.',
      certainty: 'observed',
    }),
    entity({
      id: 'service-stripe',
      kind: 'service',
      layer: 'service',
      humanLabel: 'Payment provider',
      technicalLabel: 'Stripe',
      description: 'External provider used for secure payment checkout.',
      certainty: 'observed',
    }),
    entity({
      id: 'service-segment',
      kind: 'service',
      layer: 'service',
      humanLabel: 'Product analytics',
      technicalLabel: 'Segment',
      description:
        'External analytics destination observed in browser traffic.',
      certainty: 'observed',
    }),
    entity({
      id: 'service-klaviyo',
      kind: 'service',
      layer: 'service',
      humanLabel: 'Email platform',
      technicalLabel: 'Klaviyo',
      description:
        'External service handling explicitly requested product updates.',
      certainty: 'observed',
    }),
  ],
  relations: [
    [
      'price-visible',
      'visible-price',
      'structure-price',
      'renders',
      'observed',
    ],
    [
      'price-format',
      'structure-price',
      'behaviour-price',
      'mutates',
      'correlated',
    ],
    [
      'price-request',
      'behaviour-price',
      'network-price',
      'initiates',
      'observed',
    ],
    [
      'price-service',
      'network-price',
      'service-pricing',
      'provided-by',
      'observed',
    ],
    ['cta-visible', 'visible-cta', 'structure-cta', 'renders', 'observed'],
    [
      'cta-listener',
      'structure-cta',
      'behaviour-checkout',
      'listens-to',
      'observed',
    ],
    [
      'cta-request',
      'behaviour-checkout',
      'network-checkout',
      'initiates',
      'observed',
    ],
    [
      'cta-service',
      'network-checkout',
      'service-stripe',
      'provided-by',
      'observed',
    ],
    [
      'toggle-visible',
      'visible-toggle',
      'structure-toggle',
      'renders',
      'observed',
    ],
    [
      'toggle-listener',
      'structure-toggle',
      'behaviour-billing',
      'listens-to',
      'observed',
    ],
    [
      'toggle-request',
      'behaviour-billing',
      'network-price',
      'initiates',
      'observed',
    ],
    ['track-page', 'visible-page', 'structure-page', 'renders', 'observed'],
    [
      'track-listener',
      'structure-page',
      'behaviour-analytics',
      'triggers',
      'correlated',
    ],
    [
      'track-request',
      'behaviour-analytics',
      'network-analytics',
      'initiates',
      'observed',
    ],
    [
      'track-service',
      'network-analytics',
      'service-segment',
      'provided-by',
      'observed',
    ],
    [
      'email-visible',
      'visible-newsletter',
      'structure-newsletter',
      'renders',
      'observed',
    ],
    [
      'email-listener',
      'structure-newsletter',
      'behaviour-newsletter',
      'listens-to',
      'observed',
    ],
    [
      'email-request',
      'behaviour-newsletter',
      'network-newsletter',
      'initiates',
      'observed',
    ],
    [
      'email-service',
      'network-newsletter',
      'service-klaviyo',
      'provided-by',
      'observed',
    ],
    [
      'page-document',
      'structure-page',
      'network-document',
      'returns',
      'observed',
    ],
    [
      'page-service',
      'network-document',
      'service-orbit',
      'provided-by',
      'observed',
    ],
    [
      'hydrate-page',
      'behaviour-hydrate',
      'structure-page',
      'mutates',
      'correlated',
    ],
  ].map(([id, from, to, kind, certainty]) => ({
    id,
    from,
    to,
    kind: kind as GlassWebTrace['relations'][number]['kind'],
    certainty: certainty as GlassWebTrace['relations'][number]['certainty'],
    evidenceIds: [`ev-${id}`],
    explanation: `${from} ${kind} ${to}`,
  })),
  events: [
    [
      'event-nav',
      0,
      'navigation',
      'Pricing page loaded',
      'network',
      ['network-document'],
    ],
    [
      'event-hydrate',
      460,
      'render',
      'Pricing controls became interactive',
      'behaviour',
      ['behaviour-hydrate'],
    ],
    [
      'event-price-request',
      720,
      'request',
      'Regional pricing requested',
      'network',
      ['network-price'],
    ],
    [
      'event-price-render',
      860,
      'mutation',
      'South African price appeared',
      'visible',
      ['visible-price', 'structure-price'],
    ],
    [
      'event-track',
      1230,
      'request',
      'Plan view measured',
      'network',
      ['network-analytics'],
    ],
    [
      'event-toggle',
      2740,
      'click',
      'Annual billing selected',
      'visible',
      ['visible-toggle'],
    ],
    [
      'event-reprice',
      2870,
      'mutation',
      'Annual price rendered',
      'visible',
      ['visible-price'],
    ],
    [
      'event-cta',
      4210,
      'click',
      'Start Pro selected',
      'visible',
      ['visible-cta'],
    ],
    [
      'event-checkout',
      4248,
      'request',
      'Checkout session requested',
      'network',
      ['network-checkout'],
    ],
    [
      'event-checkout-response',
      4432,
      'response',
      'Checkout session created',
      'service',
      ['service-stripe'],
    ],
    [
      'event-newsletter',
      5730,
      'submit',
      'Product updates requested',
      'visible',
      ['visible-newsletter'],
    ],
    [
      'event-newsletter-request',
      5754,
      'request',
      'Subscriber sent to email platform',
      'network',
      ['network-newsletter'],
    ],
  ].map(([id, timestamp, kind, label, layer, entityIds]) => ({
    id: id as string,
    timestamp: timestamp as number,
    kind: kind as GlassWebTrace['events'][number]['kind'],
    label: label as string,
    layer: layer as GlassWebTrace['events'][number]['layer'],
    entityIds: entityIds as string[],
    certainty: 'observed' as const,
  })),
  evidence: [],
  focuses: [
    {
      id: 'price',
      label: 'This price',
      question: 'Why am I seeing R1,499?',
      summary: 'The R1,499 price came from Orbit’s pricing service.',
      detail:
        'The page asked for the South African Pro price, received R1,499, and displayed it here. GlassWeb saw the events happen together but cannot see the private code joining the final two moments.',
      entityIds: [
        'visible-price',
        'structure-price',
        'behaviour-price',
        'network-price',
        'service-pricing',
      ],
      relationIds: [
        'price-visible',
        'price-format',
        'price-request',
        'price-service',
      ],
      surfaceEntityId: 'visible-price',
      finding:
        'AI crawlers that do not execute JavaScript never receive this price.',
    },
    {
      id: 'checkout',
      label: 'Start Pro',
      question: 'Where does Start Pro take my customer?',
      summary: 'Start Pro creates a secure checkout with Stripe.',
      detail:
        'The customer clicks Start Pro, Orbit starts one checkout, and Stripe returns the payment page. GlassWeb did not see any unexpected company in between.',
      entityIds: [
        'visible-cta',
        'structure-cta',
        'behaviour-checkout',
        'network-checkout',
        'service-stripe',
      ],
      relationIds: [
        'cta-visible',
        'cta-listener',
        'cta-request',
        'cta-service',
      ],
      surfaceEntityId: 'visible-cta',
    },
    {
      id: 'analytics',
      label: 'Who gets data',
      question: 'Which outside company is contacted?',
      summary: 'Segment receives a “Plan Viewed” message from this page.',
      detail:
        'The message is sent shortly after the Pro card appears. GlassWeb keeps the destination and timing, but it does not save the message body or anyone’s identity.',
      entityIds: [
        'visible-page',
        'structure-page',
        'behaviour-analytics',
        'network-analytics',
        'service-segment',
      ],
      relationIds: [
        'track-page',
        'track-listener',
        'track-request',
        'track-service',
      ],
      surfaceEntityId: 'visible-page',
    },
    {
      id: 'ai',
      label: 'What AI sees',
      question: 'Will AI tools see my prices?',
      summary: 'AI can read the plan names, but some tools may miss the prices.',
      detail:
        'The first version of the page contains the plan names. A real browser does extra work to add the prices later, so AI tools that leave early never receive the amount.',
      entityIds: [
        'visible-price',
        'structure-price',
        'behaviour-hydrate',
        'network-price',
        'service-pricing',
      ],
      relationIds: [
        'price-visible',
        'price-format',
        'price-request',
        'price-service',
      ],
      surfaceEntityId: 'visible-price',
      suggestedLens: 'ai',
      finding: 'Put the prices in the first version of the page so AI can see them.',
    },
    {
      id: 'newsletter',
      label: 'Email signup',
      question: 'Where does this email address go?',
      summary: 'The signup goes to Klaviyo. GlassWeb does not save the email.',
      detail:
        'GlassWeb saw the signup leave the page and reach Klaviyo. It remembered the destination and discarded the actual email address before saving the recording.',
      entityIds: [
        'visible-newsletter',
        'structure-newsletter',
        'behaviour-newsletter',
        'network-newsletter',
        'service-klaviyo',
      ],
      relationIds: [
        'email-visible',
        'email-listener',
        'email-request',
        'email-service',
      ],
      surfaceEntityId: 'visible-newsletter',
    },
  ],
  redaction: {
    policyVersion: 'glassweb-safe-metadata-v1',
    appliedAt: '2026-09-02T18:00:06.200Z',
    removed: [
      'Cookie values',
      'Authorization headers',
      'Form values',
      'Request and response bodies',
      'URL query values',
    ],
    retained: [
      'Hostnames and redacted routes',
      'Methods and status codes',
      'Timing and MIME types',
      'Safe interface labels',
      'Evidence certainty',
    ],
  },
});
